name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.5

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build
      run: go build -v .
